/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.DTOIndex;
import Controller.DTOSearch;
import java.awt.Point;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aleep
 */
public class Main extends javax.swing.JFrame {
    
    DTOIndex dtoi = new DTOIndex();
    DTOSearch dtos = new DTOSearch();

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        tablaresults.getColumn("Pos").setMaxWidth(100);
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(jLabel1.CENTER);
        tablaresults.getColumnModel().getColumn(0).setCellRenderer( centerRenderer );
        tablaresults.addMouseListener(new java.awt.event.MouseAdapter() {
                                public void mouseClicked(java.awt.event.MouseEvent evt) {
                                    tablaresultsMouseClicked(evt);
                                }});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wmain = new javax.swing.JTabbedPane();
        tabindex = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pathlab = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        indexbrowse = new javax.swing.JButton();
        dirlab = new javax.swing.JLabel();
        indexlab = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaindex = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listadir = new javax.swing.JList<>();
        addIndex = new javax.swing.JButton();
        removeindex = new javax.swing.JButton();
        indexbutton = new javax.swing.JButton();
        tabsearcher = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        queryfield = new javax.swing.JTextField();
        processbut = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaresults = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        labindexname = new javax.swing.JLabel();
        browseindex = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        maxhits = new javax.swing.JSpinner();
        resultscountlabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        wmain.setName(""); // NOI18N

        jLabel1.setText("COLLECTION PATH:");

        pathlab.setText("<<No directory has been selected yet>>");

        indexbrowse.setText("Browse");
        indexbrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indexbrowseActionPerformed(evt);
            }
        });

        dirlab.setText("Directories");

        indexlab.setText("To index");

        jScrollPane1.setViewportView(listaindex);

        jScrollPane2.setViewportView(listadir);

        addIndex.setText(">");
        addIndex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addIndexActionPerformed(evt);
            }
        });

        removeindex.setText("<");
        removeindex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeindexActionPerformed(evt);
            }
        });

        indexbutton.setText("Index");
        indexbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indexbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabindexLayout = new javax.swing.GroupLayout(tabindex);
        tabindex.setLayout(tabindexLayout);
        tabindexLayout.setHorizontalGroup(
            tabindexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabindexLayout.createSequentialGroup()
                .addGroup(tabindexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
                    .addGroup(tabindexLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1)
                        .addGap(30, 30, 30)
                        .addGroup(tabindexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(indexbrowse)
                            .addComponent(pathlab, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(tabindexLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(tabindexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tabindexLayout.createSequentialGroup()
                                .addComponent(jScrollPane2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(tabindexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addIndex)
                                    .addComponent(removeindex))
                                .addGap(24, 24, 24))
                            .addGroup(tabindexLayout.createSequentialGroup()
                                .addComponent(dirlab)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(tabindexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(indexlab)
                            .addGroup(tabindexLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(indexbutton)))))
                .addContainerGap())
        );
        tabindexLayout.setVerticalGroup(
            tabindexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabindexLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(tabindexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(pathlab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(indexbrowse)
                .addGap(36, 36, 36)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tabindexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(indexlab, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dirlab))
                .addGroup(tabindexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabindexLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(addIndex)
                        .addGap(18, 18, 18)
                        .addComponent(removeindex)
                        .addContainerGap())
                    .addGroup(tabindexLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE))
                    .addGroup(tabindexLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabindexLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(indexbutton)
                        .addGap(27, 27, 27))))
        );

        wmain.addTab("Index", tabindex);

        jLabel2.setText("Query:");

        processbut.setText("Process query");
        processbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processbutActionPerformed(evt);
            }
        });

        jLabel3.setText("Results:");

        tablaresults.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pos", "Name", "Path"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tablaresults);

        jLabel4.setText("Current index:");

        labindexname.setText("<<No index has been selected yet>>");

        browseindex.setText("Browse");
        browseindex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseindexActionPerformed(evt);
            }
        });

        jLabel5.setText("Hits:");

        maxhits.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        javax.swing.GroupLayout tabsearcherLayout = new javax.swing.GroupLayout(tabsearcher);
        tabsearcher.setLayout(tabsearcherLayout);
        tabsearcherLayout.setHorizontalGroup(
            tabsearcherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabsearcherLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabsearcherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3)
                    .addGroup(tabsearcherLayout.createSequentialGroup()
                        .addGroup(tabsearcherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tabsearcherLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(resultscountlabel))
                            .addGroup(tabsearcherLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(tabsearcherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(browseindex)
                                    .addComponent(labindexname))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(tabsearcherLayout.createSequentialGroup()
                        .addGroup(tabsearcherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tabsearcherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(queryfield)
                            .addGroup(tabsearcherLayout.createSequentialGroup()
                                .addComponent(maxhits, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)
                                .addComponent(processbut)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE))
                .addContainerGap())
        );
        tabsearcherLayout.setVerticalGroup(
            tabsearcherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabsearcherLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabsearcherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(labindexname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(browseindex)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabsearcherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(queryfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tabsearcherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(processbut)
                    .addComponent(jLabel5)
                    .addComponent(maxhits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabsearcherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(resultscountlabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        wmain.addTab("Search Engine", tabsearcher);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(wmain)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(wmain)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void indexbrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indexbrowseActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.showOpenDialog(this);
        File folder = chooser.getSelectedFile();
        try{
            pathlab.setText(folder.getAbsolutePath());
            //-------------------------------------
            dtoi.loadFolders(pathlab, listadir);
        }catch(NullPointerException e){
            
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error: stopwords");
        }
    }//GEN-LAST:event_indexbrowseActionPerformed

    private void addIndexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addIndexActionPerformed
        // TODO add your handling code here:
        dtoi.addToIndex(listadir, listaindex);
    }//GEN-LAST:event_addIndexActionPerformed

    private void removeindexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeindexActionPerformed
        // TODO add your handling code here:
        dtoi.removeFrom(listaindex);
    }//GEN-LAST:event_removeindexActionPerformed

    private void indexbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indexbuttonActionPerformed
        // TODO add your handling code here:
        dtoi.index(listaindex);
    }//GEN-LAST:event_indexbuttonActionPerformed

    private void processbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processbutActionPerformed
        // TODO add your handling code here:
        int x = (int)maxhits.getValue();
        dtos.search(queryfield.getText(), x, tablaresults, resultscountlabel);
        //DefaultTableModel model = (DefaultTableModel) tablaresults.getModel();
        //model.addRow(new Object[]{22, "test000", "teettet"});
    }//GEN-LAST:event_processbutActionPerformed

    private void browseindexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseindexActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.showOpenDialog(this);
        File folder = chooser.getSelectedFile();
        try{
            labindexname.setText(folder.getAbsolutePath());
            //-------------------------------------
            dtos.loadIndex(labindexname);
        }catch(NullPointerException e){
            
        }
    }//GEN-LAST:event_browseindexActionPerformed
    private void tablaresultsMouseClicked(MouseEvent e){
        JTable table =(JTable) e.getSource();
        Point point = e.getPoint();
        int row = table.rowAtPoint(point);
        if (e.getClickCount() == 2) {
            String path = (String) table.getValueAt(row, 2);
            try {
                Runtime.getRuntime().exec("explorer.exe /select," + path);
            } catch (IOException ex) {
                
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                //System.out.println(info.getName());
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
            
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addIndex;
    private javax.swing.JButton browseindex;
    private javax.swing.JLabel dirlab;
    private javax.swing.JButton indexbrowse;
    private javax.swing.JButton indexbutton;
    private javax.swing.JLabel indexlab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel labindexname;
    private javax.swing.JList<String> listadir;
    private javax.swing.JList<String> listaindex;
    private javax.swing.JSpinner maxhits;
    private javax.swing.JLabel pathlab;
    private javax.swing.JButton processbut;
    private javax.swing.JTextField queryfield;
    private javax.swing.JButton removeindex;
    private javax.swing.JLabel resultscountlabel;
    private javax.swing.JPanel tabindex;
    private javax.swing.JTable tablaresults;
    private javax.swing.JPanel tabsearcher;
    private javax.swing.JTabbedPane wmain;
    // End of variables declaration//GEN-END:variables
}
